services:
  #MySQL Service
  mysql:
    image: mysql:latest
    container_name: mysql_container
    volumes:
      - ./db_data:/var/lib/mysql
    env_file:
      - ./envs/mysql.env
    restart: always

  #WordPress Service
  wordpress:
    image: wordpress:latest
    container_name: wp_container
    depends_on:
      - mysql
    volumes:
      - ./wp_data:/var/www/html
      - ../..:/var/www/html/wp-content/plugins/wp-meteouniparthenope-plugin
      - ../../plugins/weatherMapDef:/var/www/html/wp-content/plugins/weather-map-def
      - ./news-magazine-x-child:/var/www/html/wp-content/themes/news-magazine-x-child
    env_file:
      - ./envs/wordpress.env
    ports:
      - 8000:80
      - 21:21
      - 22:22
